### ISSUE TITLE
Feature request: Avoid empty reads

### ISSUE THREAD

**Issue by reineckef** [qiaseq/read-trimmer#3]
Hi,
I have found empty R2 reads (no bases) in some RNA runs. STAR does not accept such reads and dies with an error. Would be great to have a switch (e.g. `--no-empty`) that will at least write a single N (and quality of 0, which is "!") for cases where no bases remain. Thanks!
Frank

**Comment by rpadmanabhan** [comment]
Hi Frank, That seems strange. What was the read length cutoffs you used , i.e. --min_primer_side_len and --min_umi_side_len , if these were non zero I don't think empty reads should be output by the trimmer, unless there is a bug.

**Comment by reineckef** [comment]
Fixed now, thanks!
